#!/usr/bin/env bash

# Builds the docker image using arguement 1 as the tag

if [ -z "$1" ]
then
    echo "Please pass tag"
    exit 1
fi

docker build ${@:2} -t "openlab.ncl.ac.uk:4567/make-place/web:$1" .
docker push "openlab.ncl.ac.uk:4567/make-place/web:$1"
