#!/usr/bin/env bash

# Builds the docker image using arguement 1 as the tag

if [ -z "$1" ]
then
    echo "Please pass tag"
    exit 1
fi

TAG="mkpl/php-platform:$1"

docker build ${@:2} -t $TAG .
docker push $TAG
