#!/usr/bin/env bash

# Script to run the code coverage and report to the console

# Setup in-memory SQLite database
export DB_HOST=none DB_USER=none DB_PASS=none DB_NAME=db.sqlite DB_PATH=:memory: DB_TYPE=SQLite3Database SITE_ENV=dev HTTP_HOST=http://localhost REQUEST_METHOD=GET

# Disable xdebug for quicker composer
php5dismod xdebug

# Enable xdebug for coverage generation
php5enmod xdebug

# Run our tests, generating a coverage report
vendor/bin/phpunit --coverage-text
