#!/usr/bin/env sh

# No longer uses input params
# PARAMS="${@:1}"


# Setup in-memory SQLite database
export DB_HOST=none DB_USER=none DB_PASS=none DB_NAME=db.sqlite DB_PATH=:memory: DB_TYPE=SQLite3Database SITE_ENV=dev HTTP_HOST=http://localhost REQUEST_METHOD=GET


# Disable xdebug for quicker composer & tests
php5dismod xdebug


while true;
do
    
    # Wait for a return & pass params to phpunit
    read -p "Run Tests [enter]: " PARAMS
    echo
    echo -e "\e[33m[========= Starting Tests =========]\e[39m"
    
    # If q entered, do exit
    [[ " q " == *" $PARAMS "* ]] && echo "Finished testing" && exit 0
    
    
    # If flush passed, flush the cache
    [[ " flush " == *" $PARAMS "* ]] && {
        unset HTTP_HOST
        framework/sake dev/tests flush=1 >> /dev/null
        export HTTP_HOST=http://localhost
    }
    
    
    if [[ " coverage-html " == *" $PARAMS "* ]]; then
        
        # If 'coverage-html' is passed, run the coverage html generator
        php5enmod xdebug
        vendor/bin/phpunit --coverage-html assets/coverage
        php5dismod xdebug
    elif [[ " coverage " == *" $PARAMS "* ]]; then
        
        # If 'coverage' is passed, run the coverage summary
        php5enmod xdebug
        vendor/bin/phpunit --coverage-text
        php5dismod xdebug
    elif [[ " all " == *" $PARAMS "* ]]; then
        
        # If 'all' is passed, run all tests
        vendor/bin/phpunit --colors
    else
        
        # Otherwise, just the whitelist group ( use @group whitelist )
        vendor/bin/phpunit --colors --group whitelist
    fi
    
done
