#!/bin/bash

# Setup in-memory SQLite database
export DB_HOST=none DB_USER=none DB_PASS=none DB_NAME=db.sqlite DB_PATH=:memory: DB_TYPE=SQLite3Database SITE_ENV=testing

# Disable xdebug for quicker composer & tests
php5dismod xdebug

# Run composer
/composer.phar install

# Run our tests
vendor/bin/phpunit mysite/tests
