#!/usr/bin/env bash

# Script to run unit tests with an in-memory database

# Setup in-memory SQLite database
export DB_HOST=none DB_USER=none DB_PASS=none DB_NAME=db.sqlite DB_PATH=:memory: DB_TYPE=SQLite3Database SITE_ENV=dev HTTP_HOST=http://localhost REQUEST_METHOD=GET

# Disable xdebug for quicker composer & tests
php5dismod xdebug

# Run our tests
vendor/bin/phpunit
